services:
  fcp-fd-probe:
    build:
      context: .
      target: production
    image: fcp-fd-probe
    container_name: fcp-fd-probe
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-probe-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
