apiVersion: v2
description: Probing service for front-door infrastructure
name: fcp-fd-probe
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.5.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
